name: NetFlow
options:
  developmentLanguage: en
  projectFormat: xcode15_0
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"

targets:
  NetFlow:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NetFlow
        excludes:
          - Preview
      - path: Shared
    resources:
      - path: NetFlow/Resources/Assets.xcassets
      - path: NetFlow/Resources/en.lproj
      - path: NetFlow/Resources/vi.lproj
      - path: NetFlow/Resources/zh.lproj
    dependencies:
      - target: NetFlowWidget
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.duyhoang.netflow
        PRODUCT_NAME: NetFlow
        SWIFT_VERSION: 5.0
        SWIFT_STRICT_CONCURRENCY: minimal
        MARKETING_VERSION: 4.2.12
        CURRENT_PROJECT_VERSION: 41
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: NetFlow/Info.plist

  NetFlowWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: NetFlowWidget
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.duyhoang.netflow.widget
        PRODUCT_NAME: NetFlowWidget
        SWIFT_VERSION: 5.0
        SWIFT_STRICT_CONCURRENCY: minimal
        MARKETING_VERSION: 4.2.12
        CURRENT_PROJECT_VERSION: 41
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: NetFlowWidget/Info.plist
        SKIP_INSTALL: YES
        APPLICATION_EXTENSION_API_ONLY: YES

  NetFlowTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NetFlowTests
    dependencies:
      - target: NetFlow
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.duyhoang.netflow.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/NetFlow.app/NetFlow"
        BUNDLE_LOADER: "$(TEST_HOST)"
